import React, {Component} from 'react'
import {View, Text, StyleSheet, ScrollView} from 'react-native'

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'grey',
  },
  header: {
    fontSize: 22,
    paddingLeft: 20,
    fontWeight: 'bold'
  },
  content: {
    margin: 20
  }
});

const privacyPolicy = () => (
  <ScrollView contentContainerStyle={styles.container}>
    <View style={{minHeight: 20}}/>
    <Text style={styles.header}>Credit Cards</Text>
    <Text style={styles.content}>All of our credit cards are processed by Stripe, the largest online payments processor.
      This means that the only part of your credit card information that ever touches our servers is the last four
      digits, card type, and expiration date. The only reason we save this information is so that you can identify what
      credit card you want to use in the app. We are fully PCI compliant and will never share this information with any
      third parties.
    </Text>
    <Text style={styles.header}>Internet Security</Text>
    <Text style={styles.content}>
      All of our internet traffic is encrypted via https, and our engineers have put an enormous amount of energy into
      developing a secure backend.
    </Text>
    <Text style={styles.header}>Personally Identifiable Information</Text>
    <Text style={styles.content}>We use your phone number, email address, and first name as part of the registration
      process and to verify your identity. We do not share this information with anyone.
    </Text>
    <Text style={styles.header}>App Generated Data</Text>
    <Text style={styles.content}>All the data generated by using the app itself (i.e. in app purchases, navigation,
      registration, login, etc.)
      is the property of AppTab Inc. and we reserve the right to use that data in any capacity. Mostly we use this in
      creating reports for restaurants and internal analytics.
    </Text>
    <Text style={styles.header}>Phone Data</Text>
    <Text style={styles.content}>We do not collect any data on your phone other than what type it is. That means that we
      don't access your contacts, pictures, camera, microphone, location data, installed apps, etc. We care about
      improving your restaurant experience, not your personal life.
    </Text>
    <Text style={styles.header}>Third Party Integrations</Text>
    <Text style={styles.content}>We will be integrating with Facebook to provide you with a better login/registration
      experience.
      We don't access any information other than your name, phone number, and email address.</Text>
    <View style={{minHeight: 30}}/>
  </ScrollView>
);

export default privacyPolicy
